spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Likhil_2002
    url: jdbc:mysql://localhost:3306/jwt_security
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

